[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_lib"
crate-type = ["cdylib"]   # Required for shared libraries

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }  # Enables Python bindings]